# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/emu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/emu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/emu/CMakeFiles /home/alex/emu/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/emu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/emu

# Build rule for target.
bin/emu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/emu
.PHONY : bin/emu

# fast build rule for target.
bin/emu/fast:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/build
.PHONY : bin/emu/fast

src/Computer.o: src/Computer.cpp.o
.PHONY : src/Computer.o

# target to build an object file
src/Computer.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Computer.cpp.o
.PHONY : src/Computer.cpp.o

src/Computer.i: src/Computer.cpp.i
.PHONY : src/Computer.i

# target to preprocess a source file
src/Computer.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Computer.cpp.i
.PHONY : src/Computer.cpp.i

src/Computer.s: src/Computer.cpp.s
.PHONY : src/Computer.s

# target to generate assembly for a file
src/Computer.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Computer.cpp.s
.PHONY : src/Computer.cpp.s

src/Mainboard.o: src/Mainboard.cpp.o
.PHONY : src/Mainboard.o

# target to build an object file
src/Mainboard.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Mainboard.cpp.o
.PHONY : src/Mainboard.cpp.o

src/Mainboard.i: src/Mainboard.cpp.i
.PHONY : src/Mainboard.i

# target to preprocess a source file
src/Mainboard.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Mainboard.cpp.i
.PHONY : src/Mainboard.cpp.i

src/Mainboard.s: src/Mainboard.cpp.s
.PHONY : src/Mainboard.s

# target to generate assembly for a file
src/Mainboard.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Mainboard.cpp.s
.PHONY : src/Mainboard.cpp.s

src/Pin.o: src/Pin.cpp.o
.PHONY : src/Pin.o

# target to build an object file
src/Pin.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Pin.cpp.o
.PHONY : src/Pin.cpp.o

src/Pin.i: src/Pin.cpp.i
.PHONY : src/Pin.i

# target to preprocess a source file
src/Pin.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Pin.cpp.i
.PHONY : src/Pin.cpp.i

src/Pin.s: src/Pin.cpp.s
.PHONY : src/Pin.s

# target to generate assembly for a file
src/Pin.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Pin.cpp.s
.PHONY : src/Pin.cpp.s

src/Socket.o: src/Socket.cpp.o
.PHONY : src/Socket.o

# target to build an object file
src/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Socket.cpp.o
.PHONY : src/Socket.cpp.o

src/Socket.i: src/Socket.cpp.i
.PHONY : src/Socket.i

# target to preprocess a source file
src/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Socket.cpp.i
.PHONY : src/Socket.cpp.i

src/Socket.s: src/Socket.cpp.s
.PHONY : src/Socket.s

# target to generate assembly for a file
src/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/Socket.cpp.s
.PHONY : src/Socket.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bin/emu.dir/build.make CMakeFiles/bin/emu.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bin/emu"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Computer.o"
	@echo "... src/Computer.i"
	@echo "... src/Computer.s"
	@echo "... src/Mainboard.o"
	@echo "... src/Mainboard.i"
	@echo "... src/Mainboard.s"
	@echo "... src/Pin.o"
	@echo "... src/Pin.i"
	@echo "... src/Pin.s"
	@echo "... src/Socket.o"
	@echo "... src/Socket.i"
	@echo "... src/Socket.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

